version: '3.8'

services:
  backend:
    build:
      context: ./backend_folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # El puerto expuesto para el frontend
    volumes:
      - ./backend_folder:/app
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_pass@db:5432/postgres_db
      - MONGO_URL=mongodb://mongo:27017/miBaseDeDatos # URL para MongoDB, usando el nombre de servicio 'mongo'
    env_file:
      - ./backend_folder/.env
    depends_on:
      - db
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Puerto expuesto para acceder a la aplicación frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - API_URL=http://backend:8000 # La URL del backend, usando el nombre de servicio 'backend'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432" # El puerto expuesto para PostgreSQL

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017" # El puerto expuesto para MongoDB
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js
