version: '3.8'

services:
  backend:
    build:
      context: ./backend_folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend_folder:/app
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_pass@db:5432/postgres_db
    depends_on:
      - db
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
