# Generated by Django 4.2.19 on 2025-02-17 11:32

from django.db import migrations

def insert_existing_data(apps, schema_editor):
    SecurityQuestion = apps.get_model('api', 'SecurityQuestion')

    existing_data = [
        {"id": 1, "question": "¿Cuál es el nombre de tu primera mascota?"},
        {"id": 2, "question": "¿Cuál es la ciudad donde naciste?"},
        {"id": 3, "question": "¿Cuál fue tu primer auto?"},
        {"id": 4, "question": "¿Cuál es el segundo nombre de tu madre?"},
        {"id": 5, "question": "¿Cómo se llamaba tu escuela primaria?"},
        {"id": 6, "question": "¿Cuál es tu comida favorita?"},
        {"id": 7, "question": "¿Cuál es el apellido de soltera de tu madre?"},
        {"id": 8, "question": "¿Cómo se llama tu mejor amigo de la infancia?"},
        {"id": 9, "question": "¿Cuál es el nombre de tu primer jefe?"},
        {"id": 10, "question": "¿Cuál fue el destino de tu primer viaje?"}
    ]

    for item in existing_data:
        SecurityQuestion.objects.update_or_create(id=item["id"], defaults={"question": item["question"]})

    Categories = apps.get_model('api', 'Categories')

    existing_data = [
        {"id": 1, "type": "Museos"},
        {"id": 2, "type": "Parques"},
        {"id": 3, "type": "Monumentos históricos"},
        {"id": 4, "type": "Playas"},
        {"id": 5, "type": "Montañas"},
        {"id": 6, "type": "Zoológicos"},
        {"id": 7, "type": "Acuarios"},
        {"id": 8, "type": "Jardines botánicos"},
        {"id": 9, "type": "Catedrales e iglesias"},
        {"id": 10, "type": "Castillos y fortalezas"},
        {"id": 11, "type": "Mercados y ferias"},
        {"id": 12, "type": "Bodegas y viñedos"},
        {"id": 13, "type": "Rutas de senderismo"},
        {"id": 14, "type": "Miradores"},
        {"id": 15, "type": "Parques de atracciones"},
        {"id": 16, "type": "Parques acuáticos"},
        {"id": 17, "type": "Cascadas"},
        {"id": 18, "type": "Cuevas y cavernas"},
        {"id": 19, "type": "Lagos y lagunas"},
        {"id": 20, "type": "Islas"}
    ]

    for item in existing_data:
        Categories.objects.update_or_create(id=item["id"], defaults={"type": item["type"]})

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(insert_existing_data)
]
